export type Protocol = 'openai' | 'anthropic' | 'responses' | 'gemini';
export type StableProtocol = Exclude<Protocol, 'gemini'>;
export type SecretSource = { type: 'env'; name: string } | { type: 'inline'; value: string } | { type: 'secret'; id: string };
export interface Credential { id: string; label: string; enabled: boolean; secret: SecretSource; status?: string | { type: string; configured: boolean; reference: string } }
export interface Model { id: string; enabled: boolean; capabilities?: Record<string, 'supported' | 'unsupported' | 'unknown'>; capabilitiesSource?: 'preset' | 'manual' | 'verified'; verifiedAt?: string }
export interface Upstream { id: string; name: string; provider: 'kimi' | 'deepseek' | 'custom'; presetId?: string; protocol: Protocol; enabled: boolean; baseUrl: string; endpoints: { generate: string; models?: string; compact?: string }; auth: { mode: 'bearer' | 'x-api-key' | 'custom-header' | 'google' | 'none' | 'pass-through' | 'oauth'; headerName?: string }; credentials: Credential[]; accountGroupId?: string; models: Model[]; priority: number; sortIndex: number; policy: Record<string, unknown>; health?: string; usage24h?: number }
export interface Route { id: string; name: string; enabled: boolean; clientProtocols: StableProtocol[]; match: { kind: 'exact' | 'glob'; value: string }; order: number; publishedModels: string[]; targets: { upstreamId: string; model: string }[] }
export interface ProxyKey { id: string; name: string; description?: string; enabled: boolean; keyPrefix?: string; createdAt?: string; expiresAt?: string | null; allowedUpstreamIds: string[]; allowedModels: string[]; rpm?: number | null; dailyTokens?: number | null; maxConcurrentRequests?: number | null; lastUsedAt?: string | null }
export interface KeyQuota { keyId: string; periodId: string | null; periodStartMs: number | null; resetAtMs: number | null; periodTimezone: string | null; activeTimezone: string; activeTimezoneVersionId: number | null; pendingTimezone: string | null; timezoneChangeEffectiveAtMs: number | null; limits: { rpm: number | null; dailyTokens: number | null; maxConcurrentRequests: number }; rpmUsed: number; reportedUsed: number; estimatedUsed: number; reserved: number; adjustmentTokens: number; activeRequests: number }
export interface RoutePreviewCandidate { upstreamId: string; model: string; actualModel: string; protocol?: string | null; upstreamProtocol?: string | null; bridge: 'native' | 'bridge' | 'unsupported'; configured: boolean; credentialState?: 'available' | 'missing' | 'cooling_down' | 'not_required' | string; configuredCredentials?: number; availableCredentials?: number; circuitState?: string; healthStatus?: string; availability?: string; eligible?: boolean; selected?: boolean; exclusionReason?: string; upstreamEnabled?: boolean; modelEnabled?: boolean; modelConfigured?: boolean }
export interface RoutePreview { matched: boolean; routeId?: string; reason?: string; runtime?: boolean; proxyKey?: 'selected' | 'not_selected' | 'unavailable' | 'unverified'; selection?: 'selected' | 'uncertain' | 'none_eligible'; candidates: RoutePreviewCandidate[] }
export interface ApiMeta { requestId?: string; observedAt?: string; dataThrough?: string; partial?: boolean; missingUsageRequests?: number; legacyLogRows?: number; grain?: string; coverage?: string; persistedRevision?: number; effectiveRevision?: number; restartRequiredFields?: string[]; nextCursor?: string }
export interface TelemetryFreshness { coverage?: string; status?: 'current' | 'stale' | 'unverified-legacy'; stale?: boolean; snapshotCompletedAtMs?: number; dataUpdatedAtMs?: number; dataThroughMs?: number | null; snapshotSequence?: number; currentSequence?: number; legacyMetadataCount?: number; legacyWritesTracked?: boolean }
export interface ApiEnvelope<T> { data: T; meta?: ApiMeta }
export interface TelemetryRecorderStatus { degraded: boolean; reason?: string; pendingEvents: number; retainedEvents: number }
export type DatabaseDiagnosticReason = 'connection_unavailable' | 'connection_closed' | 'ping_failed' | 'database_not_configured' | 'sqlite_metrics_unavailable';
export interface DatabaseHealth { status: 'available' | 'unavailable'; scope: 'connection'; reason: DatabaseDiagnosticReason | null }
export interface DatabaseCapacity { pageCount: number | null; pageSizeBytes: number | null; freePages: number | null; allocatedBytes: number | null; freeBytes: number | null; reason: DatabaseDiagnosticReason | null }
export interface DatabaseDiagnostic { health: DatabaseHealth; capacity: DatabaseCapacity }
export interface ListenerAddress { bindAddress: string; port: number }
export interface ListenerStatus { enabled: boolean; configured: ListenerAddress; actual: ListenerAddress | null }
export interface System { instanceId?: string; status?: string; persistedRevision?: number; effectiveRevision?: number; restartRequiredFields?: string[]; publicProxyBaseUrl?: string; publicAdminBaseUrl?: string; timezone?: string; listeners?: { proxy: ListenerStatus; admin: ListenerStatus } | null; databases?: { control?: DatabaseDiagnostic | null; telemetry?: DatabaseDiagnostic | null }; telemetryRecorder?: TelemetryRecorderStatus }
export interface ProductionSuccessRate { scope: 'production'; definition: string;
  status: 'exact' | 'no_admitted_ended' | 'partial_unknown_admission'; value: number | null;
  completed: number; endedAdmitted: number; excludedPreAdmissionRejected: number;
  unknownAdmissionEnded: number; excludedLegacyLogRows: number;
  measurement: 'exact_detail_snapshot' | 'covered_live_minute_plus_detail_tails' }
export interface Overview { logicalRequests?: number; legacyLogRows?: number; succeeded?: number; failed?: number; cancelled?: number; inputTokens?: number; outputTokens?: number; firstTokenP95Ms?: number | null; firstTokenP95Status?: 'exact' | 'approximate' | 'unsupported_live_preaggregate'; cacheReadTokens?: number | null; missingUsageRequests?: number | null; productionSuccessRate?: ProductionSuccessRate; freshness?: TelemetryFreshness; usage?: { coverage?: string; partial?: boolean; legacyLogRows?: number }; upstreamHealth?: { id: string; name: string; status: string }[]; recentErrors?: { requestId: string; message: string }[] }
export interface UsageSummary { logicalRequests?: number; attempts?: number; legacyLogRows?: number; inputTokens?: number; outputTokens?: number; cacheReadTokens?: number | null; cacheWriteTokens?: number | null; missingUsageRequests?: number | null; unpricedAttempts?: number; costByCurrency?: Record<string, number>; estimatedCost?: number; currency?: string; grain?: string; coverage?: string; partial?: boolean; freshness?: TelemetryFreshness }
export interface SeriesPoint { time: string; requests?: number; tokens?: number; errors?: number }
export type UsageGroupBy = 'keyId' | 'upstreamId' | 'model' | 'protocol' | 'source';
export interface UsageBreakdown { id?: string; label: string; requests?: number; upstreamAttempts?: number; inputTokens?: number; outputTokens?: number; cost?: number | null; currency?: string | null; costByCurrency?: Record<string, number>; unpricedAttempts?: number; partial?: boolean; metricsSemantics?: { requests: string; attempts: string; upstreamFilterMode: 'final' | 'attempt' }; requestMetrics?: { logicalRequests: number; completed: number; failed: number; legacyLogRows: number }; attemptMetrics?: { upstreamAttempts: number; inputTokens: number; outputTokens: number; missingUsageAttempts: number; costByCurrency: Record<string, number>; unpricedAttempts: number } }
export interface RequestRow { id: string; requestId?: string; startedAt: string; keyId?: string; requestedModel?: string; actualModel?: string; upstreamId?: string; status: string; durationMs?: number; inputTokens?: number; outputTokens?: number; usageStatus?: string; error?: { code?: string; message?: string } }
export interface Attempt { id: string; upstreamId?: string; model?: string; status: string; startedAt?: string; durationMs?: number; error?: { code?: string; message?: string } }
export interface Preset { id: string; name: string; provider: Upstream['provider']; protocol: Protocol; baseUrl: string; endpoints: Upstream['endpoints']; auth: Upstream['auth']; models?: Model[] }
export interface Account { id: string; name?: string; provider: string; type: string; status: string; expiresAt: string | null; upstreamIds?: string[]; isDefault?: boolean; refreshAvailable: boolean; lastError?: string }
export interface Capability { provider: string; deviceFlow?: boolean; clientCredentials?: boolean }
export interface Job { id: string; type: string; status: string; progress?: number; error?: string; createdAt?: string }
export interface Pricing { id: string; versionId: string; versionSequence: number; provider?: string; model: string; currency: string; inputPerMillion: number | string; outputPerMillion: number | string; cacheReadPerMillion?: number | string; cacheWritePerMillion?: number | string; cacheWrite5mPerMillion?: number | string; cacheWrite1hPerMillion?: number | string; cacheWriteIncludedInInput?: boolean; effectiveFrom: string; upstreamId?: string }
export interface Config { schemaVersion: number; revision: number; server?: { port?: number; bindAddress?: string; publicProxyBaseUrl?: string; maxBodyBytes?: number; maxAttempts?: number; connectTimeoutMs?: number; firstByteTimeoutMs?: number; streamIdleTimeoutMs?: number; totalRequestTimeoutMs?: number; trustedProxyCidrs?: string[]; [key: string]: unknown }; admin?: { enabled?: boolean; port?: number; bindAddress?: string; publicAdminBaseUrl?: string; sessionTtlSeconds?: number; [key: string]: unknown }; storage?: { dataDir?: string; flushIntervalMs?: number; batchSize?: number; requestRetentionDays?: number; minuteRetentionDays?: number; hourRetentionDays?: number; dailyRetentionDays?: number; [key: string]: unknown }; quota?: { timezone?: string; [key: string]: unknown }; [key: string]: unknown }
