import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { get, query } from '../api/client';
import type { Route, System } from '../api/types';
import { Panel, State } from '../components/ui';

export function Connect() {
  const [client,setClient]=useState('curl'); const [model,setModel]=useState(''); const routes=useQuery({queryKey:['routes'],queryFn:async()=>(await get<Route[]>('/routes')).data}); const system=useQuery({queryKey:['system'],queryFn:async()=>(await get<System>('/system')).data}); const templates=useQuery({queryKey:['connect-template',client,model],queryFn:async()=>(await get<{baseUrl?:string;model?:string;apiKey?:string;protocol?:string;snippet?:string;templates?:Record<string,string>}>('/connect/templates'+query({client,model:model||undefined}))).data}); const models=[...new Set(routes.data?.filter(r=>r.enabled).flatMap(r=>r.publishedModels)??[])]; const base=templates.data?.baseUrl; const selectedModel=templates.data?.model; const snippet=templates.data?.snippet??templates.data?.templates?.[client]??(base&&selectedModel?client==='curl'?`curl ${base.replace(/\/$/,'')}/v1/chat/completions \\\n+  -H 'Authorization: Bearer <YOUR_MODEL_ROUTER_KEY>' \\\n+  -H 'Content-Type: application/json' \\\n+  -d '{"model":"${selectedModel}","messages":[{"role":"user","content":"Hello"}]}'`:client==='openai'?`const client = new OpenAI({ baseURL: '${base.replace(/\/$/,'')}/v1', apiKey: '<YOUR_MODEL_ROUTER_KEY>' });\nawait client.chat.completions.create({ model: '${selectedModel}', messages: [{ role: 'user', content: 'Hello' }] });`:`const client = new Anthropic({ baseURL: '${base.replace(/\/$/,'')}', apiKey: '<YOUR_MODEL_ROUTER_KEY>' });\nawait client.messages.create({ model: '${selectedModel}', max_tokens: 512, messages: [{ role: 'user', content: 'Hello' }] });`:undefined);
  return <><div className="page-title"><div><p className="eyebrow">INTEGRATION</p><h1>接入指南</h1><p>复制配置片段，并替换为你的代理访问 Key</p></div></div><div className="grid-two"><Panel title="连接信息"><div className="summary-list"><div>公开代理地址 <code>{templates.data?.baseUrl??system.data?.publicProxyBaseUrl??'未配置'}</code></div><div>已发布模型 <strong>{models.length}</strong></div></div><div className="form-grid"><label className="field"><span>客户端</span><select value={client} onChange={e=>setClient(e.target.value)}><option value="curl">curl</option><option value="openai">OpenAI SDK</option><option value="anthropic">Anthropic SDK</option></select></label><label className="field"><span>模型</span><select value={model} onChange={e=>setModel(e.target.value)}><option value="">选择模型</option>{models.map(m=><option key={m}>{m}</option>)}</select></label></div><p className="muted">公开地址由服务端配置；不会从浏览器地址推断。</p></Panel><Panel title="配置模板"><State loading={templates.isPending} error={templates.error} retry={()=>templates.refetch()} empty={!snippet}><pre className="response-output">{snippet}</pre><button onClick={()=>navigator.clipboard.writeText(snippet??'')}>复制模板</button></State></Panel></div></>;
}
