import { useQuery } from '@tanstack/react-query';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { get, query, timeWindow } from '../api/client';
import type { Attempt, RequestRow } from '../api/types';
import { Badge, Panel, State, formatDate, formatNumber } from '../components/ui';

export function Requests() {
  const { id } = useParams(); const [params,setParams] = useSearchParams(); const filters = { cursor: params.get('cursor') ?? undefined, status: params.get('status') ?? undefined, model: params.get('model') ?? undefined, keyId: params.get('keyId') ?? undefined, upstreamId: params.get('upstreamId') ?? undefined, ...timeWindow(params.get('range') ?? '24h') };
  const rows = useQuery({ queryKey: ['requests',filters], queryFn: () => get<RequestRow[]>('/requests'+query(filters)), placeholderData: previous=>previous, refetchInterval: filters.cursor ? false : 30000 });
  function set(k:string,v:string) { const next=new URLSearchParams(params); if(v) next.set(k,v); else next.delete(k); if(k!=='cursor') next.delete('cursor'); setParams(next); }
  return <><div className="page-title"><div><p className="eyebrow">TRACE</p><h1>请求日志</h1><p>逐个逻辑请求与尝试链</p></div></div><div className="filters"><select aria-label="状态" value={filters.status ?? ''} onChange={e=>set('status',e.target.value)}><option value="">全部状态</option><option value="succeeded">成功</option><option value="failed">失败</option><option value="cancelled">取消</option></select><input aria-label="模型筛选" placeholder="模型" value={filters.model ?? ''} onChange={e=>set('model',e.target.value)}/><input aria-label="Key ID 筛选" placeholder="Key ID" value={filters.keyId ?? ''} onChange={e=>set('keyId',e.target.value)}/><input aria-label="上游 ID 筛选" placeholder="上游 ID" value={filters.upstreamId ?? ''} onChange={e=>set('upstreamId',e.target.value)}/></div><div className="split wide"><Panel title="请求"><State loading={rows.isPending} error={rows.error} retry={()=>rows.refetch()} empty={!rows.data?.data.length}><div className="table-wrap"><table><thead><tr><th>时间</th><th>请求 ID</th><th>模型</th><th>上游</th><th>状态</th><th>耗时</th><th>Token</th></tr></thead><tbody>{rows.data?.data.map(r=><tr key={r.id}><td>{formatDate(r.startedAt)}</td><td><Link to={`/requests/${r.id}${location.search}`}><code>{r.requestId ?? r.id}</code></Link></td><td>{r.requestedModel ?? '—'}<small>{r.actualModel && r.actualModel!==r.requestedModel ? `→ ${r.actualModel}` : ''}</small></td><td>{r.upstreamId ?? '—'}</td><td><Badge tone={r.status==='succeeded'?'good':r.status==='failed'?'bad':'warn'}>{r.status}</Badge></td><td>{r.durationMs == null?'—':`${formatNumber(r.durationMs)} ms`}</td><td>{r.usageStatus==='missing'?'未知':`${formatNumber(r.inputTokens)} / ${formatNumber(r.outputTokens)}`}</td></tr>)}</tbody></table></div><div className="actions"><button disabled={!filters.cursor} onClick={()=>set('cursor','')}>第一页</button><button disabled={!rows.data?.meta?.nextCursor} onClick={()=>set('cursor',rows.data?.meta?.nextCursor ?? '')}>下一页</button></div></State></Panel>{id && <RequestDetail id={id}/>}</div></>;
}
function RequestDetail({id}:{id:string}) { const detail=useQuery({queryKey:['request',id],queryFn:async()=>(await get<RequestRow>(`/requests/${id}`)).data}); const attempts=useQuery({queryKey:['attempts',id],queryFn:async()=>(await get<Attempt[]>(`/requests/${id}/attempts`)).data}); return <Panel title="请求详情" action={<Link to={'/requests'+location.search}>关闭</Link>}><State loading={detail.isPending} error={detail.error} retry={()=>detail.refetch()}><div className="summary-list"><div>请求 ID <code>{detail.data?.requestId ?? id}</code></div><div>实际模型 <strong>{detail.data?.actualModel ?? '—'}</strong></div><div>最终状态 <strong>{detail.data?.status}</strong></div><div>错误 <strong>{detail.data?.error?.message ?? '—'}</strong></div></div></State><h3>尝试时间线</h3><State loading={attempts.isPending} error={attempts.error} retry={()=>attempts.refetch()} empty={!attempts.data?.length}><ol className="timeline">{attempts.data?.map(a=><li key={a.id}><strong>{a.status}</strong> · {a.upstreamId ?? '—'} / {a.model ?? '—'}<small>{formatDate(a.startedAt)} · {a.durationMs ?? '—'} ms</small>{a.error && <p>{a.error.code}: {a.error.message}</p>}</li>)}</ol></State></Panel>; }
