import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { get, post, query, timeWindow } from '../api/client';
import type { ProxyKey, SeriesPoint, Upstream, UsageBreakdown, UsageSummary } from '../api/types';
import { Chart, ErrorNotice, Panel, State, formatNumber } from '../components/ui';
import { TelemetryProvenance } from './overview';

export function Usage() {
  const [params,setParams] = useSearchParams(); const [exportError,setExportError] = useState<unknown>(); const [exportJob,setExportJob] = useState<{jobId:string;downloadUrl:string}>();
  const groupBy = params.get('groupBy') ?? 'upstreamId';
  const filters = { ...timeWindow(params.get('range') ?? '24h'), keyId: params.get('keyId') ?? undefined, upstreamId: params.get('upstreamId') ?? undefined, upstreamFilterMode: params.get('upstreamFilterMode') ?? 'final', model: params.get('model') ?? undefined, protocol: params.get('protocol') ?? undefined, source: params.get('source') ?? 'proxy' };
  const path = query(filters); const summary = useQuery({ queryKey: ['usage-summary',path], queryFn: () => get<UsageSummary>('/usage/summary'+path), refetchInterval: 30000 }); const trend = useQuery({ queryKey: ['usage-timeseries',path], queryFn: async () => (await get<SeriesPoint[]>('/usage/timeseries'+path)).data }); const breakdownPath = `${path}${path ? '&' : '?'}groupBy=${encodeURIComponent(groupBy)}`; const breakdown = useQuery({ queryKey: ['usage-breakdown',breakdownPath], queryFn: async () => (await get<UsageBreakdown[]>('/usage/breakdown'+breakdownPath)).data }); const keys = useQuery({ queryKey: ['keys'], queryFn: async () => (await get<ProxyKey[]>('/keys')).data }); const upstreams = useQuery({ queryKey: ['upstreams'], queryFn: async () => (await get<Upstream[]>('/upstreams')).data });
  const exportStatus=useQuery({queryKey:['export-job',exportJob?.jobId],enabled:!!exportJob,queryFn:async()=>(await get<{status:string;error?:string}>(`/jobs/${exportJob!.jobId}`)).data,refetchInterval:q=>['completed','failed','cancelled','interrupted'].includes(q.state.data?.status??'')?false:1500});
  function set(k: string,v: string) { const next = new URLSearchParams(params); if (v) next.set(k,v); else next.delete(k); setParams(next); }
  async function exportCsv() { try { const r = await post<{ jobId: string; downloadUrl:string }>('/exports', { type: 'usage', filters, format: 'csv' }, { idempotencyKey: crypto.randomUUID() }); setExportJob({jobId:r.data.jobId,downloadUrl:r.data.downloadUrl}); setExportError(undefined); } catch (err) { setExportError(err); } }
  const d=summary.data?.data;
  const noRecords = d?.logicalRequests === 0 && d?.attempts === 0;
  return <>
    <div className="page-title"><div><p className="eyebrow">ANALYTICS</p><h1>用量分析</h1><p>请求、Token 与估算费用</p></div><button onClick={exportCsv}>导出 CSV</button></div>
    <ErrorNotice error={exportError}/>
    {exportJob && <p className="notice">导出任务：<code>{exportJob.jobId}</code> · {exportStatus.data?.status??'查询中'}。{exportStatus.data?.status==='completed'&&<a href={exportJob.downloadUrl}>下载 CSV</a>}{exportStatus.data?.error&&<span className="form-error">{exportStatus.data.error}</span>}</p>}
    <div className="filters"><select aria-label="访问 Key" value={filters.keyId ?? ''} onChange={e=>set('keyId',e.target.value)}><option value="">所有 Key</option>{keys.data?.map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select><label>上游筛选口径 <select aria-label="上游筛选口径" value={filters.upstreamFilterMode} onChange={e=>set('upstreamFilterMode',e.target.value)}><option value="final">最终上游</option><option value="attempt">参与尝试上游</option></select></label><select aria-label="上游" value={filters.upstreamId ?? ''} onChange={e=>set('upstreamId',e.target.value)}><option value="">所有上游</option>{upstreams.data?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input aria-label="模型" placeholder="模型" value={filters.model ?? ''} onChange={e=>set('model',e.target.value)}/><select aria-label="协议" value={filters.protocol ?? ''} onChange={e=>set('protocol',e.target.value)}><option value="">全部协议</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="responses">Responses</option></select><select aria-label="流量来源" value={filters.source} onChange={e=>set('source',e.target.value)}><option value="proxy">生产代理</option><option value="playground">测试台</option><option value="all">全部</option></select></div>
    <State loading={summary.isPending} error={summary.error} retry={()=>summary.refetch()}>
      <div className="stats"><div className="stat"><span>逻辑请求 / 尝试</span><strong>{formatNumber(d?.logicalRequests)} / {formatNumber(d?.attempts)}</strong></div><div className="stat"><span>输入 / 输出 Token</span><strong>{noRecords ? '—' : formatNumber(d?.inputTokens)} / {noRecords ? '—' : formatNumber(d?.outputTokens)}</strong></div><div className="stat"><span>缓存读 / 写</span><strong>{noRecords ? '—' : formatNumber(d?.cacheReadTokens)} / {noRecords ? '—' : formatNumber(d?.cacheWriteTokens)}</strong></div><div className="stat"><span>未知用量</span><strong>{noRecords ? '—' : formatNumber(d?.missingUsageRequests)}</strong></div></div>
      {noRecords && <p className="muted">当前筛选范围没有原生请求或尝试记录；历史日志行另列。Token 和用量指标不显示为 0。</p>}
      {(d?.legacyLogRows ?? 0) > 0 && <p className="notice" role="status">历史日志行：<strong>{formatNumber(d?.legacyLogRows)}</strong>。旧日志无法去重重试；这些行单独统计，未计入上方逻辑请求数或尝试数。</p>}
      <TelemetryProvenance meta={summary.data?.meta} freshness={d?.freshness} grain={d?.grain} coverage={d?.coverage} legacyLogRows={d?.legacyLogRows}/>
      <Panel title="估算费用">{d?.costByCurrency && Object.keys(d.costByCurrency).length ? Object.entries(d.costByCurrency).map(([currency,amount])=><div className="row" key={currency}><span>{currency} 小计</span><strong>{amount}</strong></div>) : d?.estimatedCost != null ? <p>{d.estimatedCost} {d.currency ?? '币种未知'}</p> : <p className="muted">暂无可计算费用</p>}{(d?.unpricedAttempts ?? 0) > 0 && <p className="notice" role="status">另有 {formatNumber(d?.unpricedAttempts)} 次尝试缺少价格，未计入以上小计。</p>}</Panel>
    </State>
    <div className="grid-two"><Panel title="请求趋势"><State loading={trend.isPending} error={trend.error} retry={()=>trend.refetch()}><Chart points={trend.data ?? []} keyName="requests"/></State></Panel><Panel title="Token 趋势"><State loading={trend.isPending} error={trend.error}><Chart points={trend.data ?? []} keyName="tokens"/></State></Panel></div>
    <Panel title="用量排行"><div className="filters"><label>排行维度 <select aria-label="排行维度" value={groupBy} onChange={e=>set('groupBy',e.target.value)}><option value="keyId">访问 Key</option><option value="upstreamId">上游</option><option value="model">模型</option><option value="protocol">协议</option><option value="source">来源</option></select></label></div>{groupBy === 'upstreamId' && <p className="notice" role="status">请求数按最终上游归属；尝试数、Token 与费用按实际参与尝试的上游统计。筛选口径：{filters.upstreamFilterMode === 'attempt' ? '参与尝试上游' : '最终上游'}。</p>}<State loading={breakdown.isPending} error={breakdown.error} retry={()=>breakdown.refetch()} empty={!breakdown.data?.length}><div className="table-wrap"><table><thead><tr><th>{({keyId:'访问 Key',upstreamId:'上游',model:'模型',protocol:'协议',source:'来源'} as Record<string,string>)[groupBy] ?? '分组'}</th><th>逻辑请求（最终归属）</th><th>实际尝试</th><th>输入 Token（尝试）</th><th>输出 Token（尝试）</th><th>费用小计（尝试）</th></tr></thead><tbody>{breakdown.data?.map((x,i)=><tr key={x.id ?? i}><td>{x.label}</td><td>{formatNumber(x.requestMetrics?.logicalRequests ?? x.requests)}</td><td>{formatNumber(x.attemptMetrics?.upstreamAttempts ?? x.upstreamAttempts)}</td><td>{formatNumber(x.attemptMetrics?.inputTokens ?? x.inputTokens)}</td><td>{formatNumber(x.attemptMetrics?.outputTokens ?? x.outputTokens)}</td><td>{Object.entries(x.attemptMetrics?.costByCurrency ?? x.costByCurrency ?? {}).length ? <>{Object.entries(x.attemptMetrics?.costByCurrency ?? x.costByCurrency ?? {}).map(([currency,amount])=><div key={currency}>{amount} {currency}</div>)}{(x.attemptMetrics?.unpricedAttempts ?? x.unpricedAttempts ?? 0) > 0 && <div>另有 {formatNumber(x.attemptMetrics?.unpricedAttempts ?? x.unpricedAttempts)} 次未计价</div>}</> : (x.attemptMetrics?.unpricedAttempts ?? x.unpricedAttempts ?? 0) > 0 ? `未知（${formatNumber(x.attemptMetrics?.unpricedAttempts ?? x.unpricedAttempts)} 次未计价）` : '暂无费用'}</td></tr>)}</tbody></table></div></State></Panel>
  </>;
}
